name = "licencias-cloudflare"
compatibility_date = "2025-06-18"
main = "src/index.js"
# workers_dev = true   ← quita o comenta esto
workers_dev = false    # porque vas a usar tu dominio personalizado

# Aquí enganchas tu Worker a todas las rutas de tu host
route = "licencias-cloudflare.storesilkify.workers.dev/*"

[vars]
GOOGLE_SHEET_ID = ""
GOOGLE_API_KEY = ""
RESEND_API_KEY = ""
FROM_EMAIL = ""
